/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as StudioTasksRouteImport } from './routes/studio.tasks'
import { Route as StudioSettingsRouteImport } from './routes/studio.settings'
import { Route as StudioResourcesRouteImport } from './routes/studio.resources'
import { Route as StudioQueueRouteImport } from './routes/studio.queue'
import { Route as StudioMessagesRouteImport } from './routes/studio.messages'
import { Route as StudioInvoicesRouteImport } from './routes/studio.invoices'
import { Route as StudioGalleriesRouteImport } from './routes/studio.galleries'
import { Route as StudioFormsRouteImport } from './routes/studio.forms'
import { Route as StudioFinancialsRouteImport } from './routes/studio.financials'
import { Route as StudioContractsRouteImport } from './routes/studio.contracts'
import { Route as StudioCalendarRouteImport } from './routes/studio.calendar'
import { Route as StudioBriefingsRouteImport } from './routes/studio.briefings'
import { Route as StudioApprovalQueueRouteImport } from './routes/studio.approval-queue'
import { Route as PortalWelcomeRouteImport } from './routes/portal.welcome'
import { Route as PortalTimelineRouteImport } from './routes/portal.timeline'
import { Route as PortalResourcesRouteImport } from './routes/portal.resources'
import { Route as PortalQuestionnairesRouteImport } from './routes/portal.questionnaires'
import { Route as PortalPortraitSequenceRouteImport } from './routes/portal.portrait-sequence'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalGalleryRouteImport } from './routes/portal.gallery'
import { Route as PortalEngagementRouteImport } from './routes/portal.engagement'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalActivityRouteImport } from './routes/portal.activity'
import { Route as PortalAccountRouteImport } from './routes/portal.account'
import { Route as StudioClientsIndexRouteImport } from './routes/studio.clients.index'
import { Route as PortalAccountIndexRouteImport } from './routes/portal.account.index'
import { Route as StudioSettingsWorkflowRouteImport } from './routes/studio.settings.workflow'
import { Route as StudioSettingsTeamRouteImport } from './routes/studio.settings.team'
import { Route as StudioSettingsStudioProfileRouteImport } from './routes/studio.settings.studio-profile'
import { Route as StudioSettingsStorageRouteImport } from './routes/studio.settings.storage'
import { Route as StudioSettingsResourcesRouteImport } from './routes/studio.settings.resources'
import { Route as StudioSettingsProfileRouteImport } from './routes/studio.settings.profile'
import { Route as StudioSettingsIntegrationsRouteImport } from './routes/studio.settings.integrations'
import { Route as StudioSettingsEmailTemplatesRouteImport } from './routes/studio.settings.email-templates'
import { Route as StudioSettingsContractorsRouteImport } from './routes/studio.settings.contractors'
import { Route as StudioSettingsContractTemplatesRouteImport } from './routes/studio.settings.contract-templates'
import { Route as StudioSettingsContractDefaultsRouteImport } from './routes/studio.settings.contract-defaults'
import { Route as StudioSettingsCalendarRouteImport } from './routes/studio.settings.calendar'
import { Route as StudioSettingsActivityLogRouteImport } from './routes/studio.settings.activity-log'
import { Route as StudioQueueHiddenRouteImport } from './routes/studio.queue.hidden'
import { Route as StudioPipelineSalesRouteImport } from './routes/studio.pipeline.sales'
import { Route as StudioPipelineProductionRouteImport } from './routes/studio.pipeline.production'
import { Route as StudioContractsTemplatesRouteImport } from './routes/studio.contracts.templates'
import { Route as StudioClientsIdRouteImport } from './routes/studio.clients.$id'
import { Route as StudioBriefingsIdRouteImport } from './routes/studio.briefings.$id'
import { Route as SignContractContractIdRouteImport } from './routes/sign.contract.$contractId'
import { Route as PortalAccountSecurityRouteImport } from './routes/portal.account.security'
import { Route as PortalAccountPartnerRouteImport } from './routes/portal.account.partner'
import { Route as PortalAccountNotificationsRouteImport } from './routes/portal.account.notifications'
import { Route as StudioSettingsEmailsIndexRouteImport } from './routes/studio.settings.emails.index'
import { Route as StudioSettingsEmailsEmailTypeRouteImport } from './routes/studio.settings.emails.$emailType'
import { Route as StudioContractsTemplatesIdRouteImport } from './routes/studio.contracts.templates.$id'
import { Route as StudioClientsIdSourcingRouteImport } from './routes/studio.clients.$id_.sourcing'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const StudioTasksRoute = StudioTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioResourcesRoute = StudioResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudioRoute,
} as any)
const StudioQueueRoute = StudioQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMessagesRoute = StudioMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInvoicesRoute = StudioInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGalleriesRoute = StudioGalleriesRouteImport.update({
  id: '/galleries',
  path: '/galleries',
  getParentRoute: () => StudioRoute,
} as any)
const StudioFormsRoute = StudioFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => StudioRoute,
} as any)
const StudioFinancialsRoute = StudioFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => StudioRoute,
} as any)
const StudioContractsRoute = StudioContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCalendarRoute = StudioCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBriefingsRoute = StudioBriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioApprovalQueueRoute = StudioApprovalQueueRouteImport.update({
  id: '/approval-queue',
  path: '/approval-queue',
  getParentRoute: () => StudioRoute,
} as any)
const PortalWelcomeRoute = PortalWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTimelineRoute = PortalTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => PortalRoute,
} as any)
const PortalResourcesRoute = PortalResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuestionnairesRoute = PortalQuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortraitSequenceRoute = PortalPortraitSequenceRouteImport.update({
  id: '/portrait-sequence',
  path: '/portrait-sequence',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGalleryRoute = PortalGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEngagementRoute = PortalEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalActivityRoute = PortalActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRoute,
} as any)
const StudioClientsIndexRoute = StudioClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => StudioRoute,
} as any)
const PortalAccountIndexRoute = PortalAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalAccountRoute,
} as any)
const StudioSettingsWorkflowRoute = StudioSettingsWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsTeamRoute = StudioSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsStudioProfileRoute =
  StudioSettingsStudioProfileRouteImport.update({
    id: '/studio-profile',
    path: '/studio-profile',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioSettingsStorageRoute = StudioSettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsResourcesRoute = StudioSettingsResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsProfileRoute = StudioSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsIntegrationsRoute =
  StudioSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioSettingsEmailTemplatesRoute =
  StudioSettingsEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioSettingsContractorsRoute =
  StudioSettingsContractorsRouteImport.update({
    id: '/contractors',
    path: '/contractors',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioSettingsContractTemplatesRoute =
  StudioSettingsContractTemplatesRouteImport.update({
    id: '/contract-templates',
    path: '/contract-templates',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioSettingsContractDefaultsRoute =
  StudioSettingsContractDefaultsRouteImport.update({
    id: '/contract-defaults',
    path: '/contract-defaults',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioSettingsCalendarRoute = StudioSettingsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudioSettingsRoute,
} as any)
const StudioSettingsActivityLogRoute =
  StudioSettingsActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioQueueHiddenRoute = StudioQueueHiddenRouteImport.update({
  id: '/hidden',
  path: '/hidden',
  getParentRoute: () => StudioQueueRoute,
} as any)
const StudioPipelineSalesRoute = StudioPipelineSalesRouteImport.update({
  id: '/pipeline/sales',
  path: '/pipeline/sales',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPipelineProductionRoute =
  StudioPipelineProductionRouteImport.update({
    id: '/pipeline/production',
    path: '/pipeline/production',
    getParentRoute: () => StudioRoute,
  } as any)
const StudioContractsTemplatesRoute =
  StudioContractsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => StudioContractsRoute,
  } as any)
const StudioClientsIdRoute = StudioClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBriefingsIdRoute = StudioBriefingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioBriefingsRoute,
} as any)
const SignContractContractIdRoute = SignContractContractIdRouteImport.update({
  id: '/sign/contract/$contractId',
  path: '/sign/contract/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAccountSecurityRoute = PortalAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PortalAccountRoute,
} as any)
const PortalAccountPartnerRoute = PortalAccountPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => PortalAccountRoute,
} as any)
const PortalAccountNotificationsRoute =
  PortalAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PortalAccountRoute,
  } as any)
const StudioSettingsEmailsIndexRoute =
  StudioSettingsEmailsIndexRouteImport.update({
    id: '/emails/',
    path: '/emails/',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioSettingsEmailsEmailTypeRoute =
  StudioSettingsEmailsEmailTypeRouteImport.update({
    id: '/emails/$emailType',
    path: '/emails/$emailType',
    getParentRoute: () => StudioSettingsRoute,
  } as any)
const StudioContractsTemplatesIdRoute =
  StudioContractsTemplatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StudioContractsTemplatesRoute,
  } as any)
const StudioClientsIdSourcingRoute = StudioClientsIdSourcingRouteImport.update({
  id: '/clients/$id_/sourcing',
  path: '/clients/$id/sourcing',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/portal/account': typeof PortalAccountRouteWithChildren
  '/portal/activity': typeof PortalActivityRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/engagement': typeof PortalEngagementRoute
  '/portal/gallery': typeof PortalGalleryRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/portrait-sequence': typeof PortalPortraitSequenceRoute
  '/portal/questionnaires': typeof PortalQuestionnairesRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/timeline': typeof PortalTimelineRoute
  '/portal/welcome': typeof PortalWelcomeRoute
  '/studio/approval-queue': typeof StudioApprovalQueueRoute
  '/studio/briefings': typeof StudioBriefingsRouteWithChildren
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/contracts': typeof StudioContractsRouteWithChildren
  '/studio/financials': typeof StudioFinancialsRoute
  '/studio/forms': typeof StudioFormsRoute
  '/studio/galleries': typeof StudioGalleriesRoute
  '/studio/invoices': typeof StudioInvoicesRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/studio/queue': typeof StudioQueueRouteWithChildren
  '/studio/resources': typeof StudioResourcesRoute
  '/studio/settings': typeof StudioSettingsRouteWithChildren
  '/studio/tasks': typeof StudioTasksRoute
  '/portal/': typeof PortalIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/portal/account/notifications': typeof PortalAccountNotificationsRoute
  '/portal/account/partner': typeof PortalAccountPartnerRoute
  '/portal/account/security': typeof PortalAccountSecurityRoute
  '/sign/contract/$contractId': typeof SignContractContractIdRoute
  '/studio/briefings/$id': typeof StudioBriefingsIdRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
  '/studio/contracts/templates': typeof StudioContractsTemplatesRouteWithChildren
  '/studio/pipeline/production': typeof StudioPipelineProductionRoute
  '/studio/pipeline/sales': typeof StudioPipelineSalesRoute
  '/studio/queue/hidden': typeof StudioQueueHiddenRoute
  '/studio/settings/activity-log': typeof StudioSettingsActivityLogRoute
  '/studio/settings/calendar': typeof StudioSettingsCalendarRoute
  '/studio/settings/contract-defaults': typeof StudioSettingsContractDefaultsRoute
  '/studio/settings/contract-templates': typeof StudioSettingsContractTemplatesRoute
  '/studio/settings/contractors': typeof StudioSettingsContractorsRoute
  '/studio/settings/email-templates': typeof StudioSettingsEmailTemplatesRoute
  '/studio/settings/integrations': typeof StudioSettingsIntegrationsRoute
  '/studio/settings/profile': typeof StudioSettingsProfileRoute
  '/studio/settings/resources': typeof StudioSettingsResourcesRoute
  '/studio/settings/storage': typeof StudioSettingsStorageRoute
  '/studio/settings/studio-profile': typeof StudioSettingsStudioProfileRoute
  '/studio/settings/team': typeof StudioSettingsTeamRoute
  '/studio/settings/workflow': typeof StudioSettingsWorkflowRoute
  '/portal/account/': typeof PortalAccountIndexRoute
  '/studio/clients/': typeof StudioClientsIndexRoute
  '/studio/clients/$id/sourcing': typeof StudioClientsIdSourcingRoute
  '/studio/contracts/templates/$id': typeof StudioContractsTemplatesIdRoute
  '/studio/settings/emails/$emailType': typeof StudioSettingsEmailsEmailTypeRoute
  '/studio/settings/emails/': typeof StudioSettingsEmailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal/activity': typeof PortalActivityRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/engagement': typeof PortalEngagementRoute
  '/portal/gallery': typeof PortalGalleryRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/portrait-sequence': typeof PortalPortraitSequenceRoute
  '/portal/questionnaires': typeof PortalQuestionnairesRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/timeline': typeof PortalTimelineRoute
  '/portal/welcome': typeof PortalWelcomeRoute
  '/studio/approval-queue': typeof StudioApprovalQueueRoute
  '/studio/briefings': typeof StudioBriefingsRouteWithChildren
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/contracts': typeof StudioContractsRouteWithChildren
  '/studio/financials': typeof StudioFinancialsRoute
  '/studio/forms': typeof StudioFormsRoute
  '/studio/galleries': typeof StudioGalleriesRoute
  '/studio/invoices': typeof StudioInvoicesRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/studio/queue': typeof StudioQueueRouteWithChildren
  '/studio/resources': typeof StudioResourcesRoute
  '/studio/settings': typeof StudioSettingsRouteWithChildren
  '/studio/tasks': typeof StudioTasksRoute
  '/portal': typeof PortalIndexRoute
  '/studio': typeof StudioIndexRoute
  '/portal/account/notifications': typeof PortalAccountNotificationsRoute
  '/portal/account/partner': typeof PortalAccountPartnerRoute
  '/portal/account/security': typeof PortalAccountSecurityRoute
  '/sign/contract/$contractId': typeof SignContractContractIdRoute
  '/studio/briefings/$id': typeof StudioBriefingsIdRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
  '/studio/contracts/templates': typeof StudioContractsTemplatesRouteWithChildren
  '/studio/pipeline/production': typeof StudioPipelineProductionRoute
  '/studio/pipeline/sales': typeof StudioPipelineSalesRoute
  '/studio/queue/hidden': typeof StudioQueueHiddenRoute
  '/studio/settings/activity-log': typeof StudioSettingsActivityLogRoute
  '/studio/settings/calendar': typeof StudioSettingsCalendarRoute
  '/studio/settings/contract-defaults': typeof StudioSettingsContractDefaultsRoute
  '/studio/settings/contract-templates': typeof StudioSettingsContractTemplatesRoute
  '/studio/settings/contractors': typeof StudioSettingsContractorsRoute
  '/studio/settings/email-templates': typeof StudioSettingsEmailTemplatesRoute
  '/studio/settings/integrations': typeof StudioSettingsIntegrationsRoute
  '/studio/settings/profile': typeof StudioSettingsProfileRoute
  '/studio/settings/resources': typeof StudioSettingsResourcesRoute
  '/studio/settings/storage': typeof StudioSettingsStorageRoute
  '/studio/settings/studio-profile': typeof StudioSettingsStudioProfileRoute
  '/studio/settings/team': typeof StudioSettingsTeamRoute
  '/studio/settings/workflow': typeof StudioSettingsWorkflowRoute
  '/portal/account': typeof PortalAccountIndexRoute
  '/studio/clients': typeof StudioClientsIndexRoute
  '/studio/clients/$id/sourcing': typeof StudioClientsIdSourcingRoute
  '/studio/contracts/templates/$id': typeof StudioContractsTemplatesIdRoute
  '/studio/settings/emails/$emailType': typeof StudioSettingsEmailsEmailTypeRoute
  '/studio/settings/emails': typeof StudioSettingsEmailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/portal/account': typeof PortalAccountRouteWithChildren
  '/portal/activity': typeof PortalActivityRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/engagement': typeof PortalEngagementRoute
  '/portal/gallery': typeof PortalGalleryRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/portrait-sequence': typeof PortalPortraitSequenceRoute
  '/portal/questionnaires': typeof PortalQuestionnairesRoute
  '/portal/resources': typeof PortalResourcesRoute
  '/portal/timeline': typeof PortalTimelineRoute
  '/portal/welcome': typeof PortalWelcomeRoute
  '/studio/approval-queue': typeof StudioApprovalQueueRoute
  '/studio/briefings': typeof StudioBriefingsRouteWithChildren
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/contracts': typeof StudioContractsRouteWithChildren
  '/studio/financials': typeof StudioFinancialsRoute
  '/studio/forms': typeof StudioFormsRoute
  '/studio/galleries': typeof StudioGalleriesRoute
  '/studio/invoices': typeof StudioInvoicesRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/studio/queue': typeof StudioQueueRouteWithChildren
  '/studio/resources': typeof StudioResourcesRoute
  '/studio/settings': typeof StudioSettingsRouteWithChildren
  '/studio/tasks': typeof StudioTasksRoute
  '/portal/': typeof PortalIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/portal/account/notifications': typeof PortalAccountNotificationsRoute
  '/portal/account/partner': typeof PortalAccountPartnerRoute
  '/portal/account/security': typeof PortalAccountSecurityRoute
  '/sign/contract/$contractId': typeof SignContractContractIdRoute
  '/studio/briefings/$id': typeof StudioBriefingsIdRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
  '/studio/contracts/templates': typeof StudioContractsTemplatesRouteWithChildren
  '/studio/pipeline/production': typeof StudioPipelineProductionRoute
  '/studio/pipeline/sales': typeof StudioPipelineSalesRoute
  '/studio/queue/hidden': typeof StudioQueueHiddenRoute
  '/studio/settings/activity-log': typeof StudioSettingsActivityLogRoute
  '/studio/settings/calendar': typeof StudioSettingsCalendarRoute
  '/studio/settings/contract-defaults': typeof StudioSettingsContractDefaultsRoute
  '/studio/settings/contract-templates': typeof StudioSettingsContractTemplatesRoute
  '/studio/settings/contractors': typeof StudioSettingsContractorsRoute
  '/studio/settings/email-templates': typeof StudioSettingsEmailTemplatesRoute
  '/studio/settings/integrations': typeof StudioSettingsIntegrationsRoute
  '/studio/settings/profile': typeof StudioSettingsProfileRoute
  '/studio/settings/resources': typeof StudioSettingsResourcesRoute
  '/studio/settings/storage': typeof StudioSettingsStorageRoute
  '/studio/settings/studio-profile': typeof StudioSettingsStudioProfileRoute
  '/studio/settings/team': typeof StudioSettingsTeamRoute
  '/studio/settings/workflow': typeof StudioSettingsWorkflowRoute
  '/portal/account/': typeof PortalAccountIndexRoute
  '/studio/clients/': typeof StudioClientsIndexRoute
  '/studio/clients/$id_/sourcing': typeof StudioClientsIdSourcingRoute
  '/studio/contracts/templates/$id': typeof StudioContractsTemplatesIdRoute
  '/studio/settings/emails/$emailType': typeof StudioSettingsEmailsEmailTypeRoute
  '/studio/settings/emails/': typeof StudioSettingsEmailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/studio'
    | '/portal/account'
    | '/portal/activity'
    | '/portal/documents'
    | '/portal/engagement'
    | '/portal/gallery'
    | '/portal/invoices'
    | '/portal/messages'
    | '/portal/portrait-sequence'
    | '/portal/questionnaires'
    | '/portal/resources'
    | '/portal/timeline'
    | '/portal/welcome'
    | '/studio/approval-queue'
    | '/studio/briefings'
    | '/studio/calendar'
    | '/studio/contracts'
    | '/studio/financials'
    | '/studio/forms'
    | '/studio/galleries'
    | '/studio/invoices'
    | '/studio/messages'
    | '/studio/queue'
    | '/studio/resources'
    | '/studio/settings'
    | '/studio/tasks'
    | '/portal/'
    | '/studio/'
    | '/portal/account/notifications'
    | '/portal/account/partner'
    | '/portal/account/security'
    | '/sign/contract/$contractId'
    | '/studio/briefings/$id'
    | '/studio/clients/$id'
    | '/studio/contracts/templates'
    | '/studio/pipeline/production'
    | '/studio/pipeline/sales'
    | '/studio/queue/hidden'
    | '/studio/settings/activity-log'
    | '/studio/settings/calendar'
    | '/studio/settings/contract-defaults'
    | '/studio/settings/contract-templates'
    | '/studio/settings/contractors'
    | '/studio/settings/email-templates'
    | '/studio/settings/integrations'
    | '/studio/settings/profile'
    | '/studio/settings/resources'
    | '/studio/settings/storage'
    | '/studio/settings/studio-profile'
    | '/studio/settings/team'
    | '/studio/settings/workflow'
    | '/portal/account/'
    | '/studio/clients/'
    | '/studio/clients/$id/sourcing'
    | '/studio/contracts/templates/$id'
    | '/studio/settings/emails/$emailType'
    | '/studio/settings/emails/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal/activity'
    | '/portal/documents'
    | '/portal/engagement'
    | '/portal/gallery'
    | '/portal/invoices'
    | '/portal/messages'
    | '/portal/portrait-sequence'
    | '/portal/questionnaires'
    | '/portal/resources'
    | '/portal/timeline'
    | '/portal/welcome'
    | '/studio/approval-queue'
    | '/studio/briefings'
    | '/studio/calendar'
    | '/studio/contracts'
    | '/studio/financials'
    | '/studio/forms'
    | '/studio/galleries'
    | '/studio/invoices'
    | '/studio/messages'
    | '/studio/queue'
    | '/studio/resources'
    | '/studio/settings'
    | '/studio/tasks'
    | '/portal'
    | '/studio'
    | '/portal/account/notifications'
    | '/portal/account/partner'
    | '/portal/account/security'
    | '/sign/contract/$contractId'
    | '/studio/briefings/$id'
    | '/studio/clients/$id'
    | '/studio/contracts/templates'
    | '/studio/pipeline/production'
    | '/studio/pipeline/sales'
    | '/studio/queue/hidden'
    | '/studio/settings/activity-log'
    | '/studio/settings/calendar'
    | '/studio/settings/contract-defaults'
    | '/studio/settings/contract-templates'
    | '/studio/settings/contractors'
    | '/studio/settings/email-templates'
    | '/studio/settings/integrations'
    | '/studio/settings/profile'
    | '/studio/settings/resources'
    | '/studio/settings/storage'
    | '/studio/settings/studio-profile'
    | '/studio/settings/team'
    | '/studio/settings/workflow'
    | '/portal/account'
    | '/studio/clients'
    | '/studio/clients/$id/sourcing'
    | '/studio/contracts/templates/$id'
    | '/studio/settings/emails/$emailType'
    | '/studio/settings/emails'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/studio'
    | '/portal/account'
    | '/portal/activity'
    | '/portal/documents'
    | '/portal/engagement'
    | '/portal/gallery'
    | '/portal/invoices'
    | '/portal/messages'
    | '/portal/portrait-sequence'
    | '/portal/questionnaires'
    | '/portal/resources'
    | '/portal/timeline'
    | '/portal/welcome'
    | '/studio/approval-queue'
    | '/studio/briefings'
    | '/studio/calendar'
    | '/studio/contracts'
    | '/studio/financials'
    | '/studio/forms'
    | '/studio/galleries'
    | '/studio/invoices'
    | '/studio/messages'
    | '/studio/queue'
    | '/studio/resources'
    | '/studio/settings'
    | '/studio/tasks'
    | '/portal/'
    | '/studio/'
    | '/portal/account/notifications'
    | '/portal/account/partner'
    | '/portal/account/security'
    | '/sign/contract/$contractId'
    | '/studio/briefings/$id'
    | '/studio/clients/$id'
    | '/studio/contracts/templates'
    | '/studio/pipeline/production'
    | '/studio/pipeline/sales'
    | '/studio/queue/hidden'
    | '/studio/settings/activity-log'
    | '/studio/settings/calendar'
    | '/studio/settings/contract-defaults'
    | '/studio/settings/contract-templates'
    | '/studio/settings/contractors'
    | '/studio/settings/email-templates'
    | '/studio/settings/integrations'
    | '/studio/settings/profile'
    | '/studio/settings/resources'
    | '/studio/settings/storage'
    | '/studio/settings/studio-profile'
    | '/studio/settings/team'
    | '/studio/settings/workflow'
    | '/portal/account/'
    | '/studio/clients/'
    | '/studio/clients/$id_/sourcing'
    | '/studio/contracts/templates/$id'
    | '/studio/settings/emails/$emailType'
    | '/studio/settings/emails/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  SignContractContractIdRoute: typeof SignContractContractIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/studio/tasks': {
      id: '/studio/tasks'
      path: '/tasks'
      fullPath: '/studio/tasks'
      preLoaderRoute: typeof StudioTasksRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/resources': {
      id: '/studio/resources'
      path: '/resources'
      fullPath: '/studio/resources'
      preLoaderRoute: typeof StudioResourcesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/queue': {
      id: '/studio/queue'
      path: '/queue'
      fullPath: '/studio/queue'
      preLoaderRoute: typeof StudioQueueRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/messages': {
      id: '/studio/messages'
      path: '/messages'
      fullPath: '/studio/messages'
      preLoaderRoute: typeof StudioMessagesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/invoices': {
      id: '/studio/invoices'
      path: '/invoices'
      fullPath: '/studio/invoices'
      preLoaderRoute: typeof StudioInvoicesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/galleries': {
      id: '/studio/galleries'
      path: '/galleries'
      fullPath: '/studio/galleries'
      preLoaderRoute: typeof StudioGalleriesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/forms': {
      id: '/studio/forms'
      path: '/forms'
      fullPath: '/studio/forms'
      preLoaderRoute: typeof StudioFormsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/financials': {
      id: '/studio/financials'
      path: '/financials'
      fullPath: '/studio/financials'
      preLoaderRoute: typeof StudioFinancialsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/contracts': {
      id: '/studio/contracts'
      path: '/contracts'
      fullPath: '/studio/contracts'
      preLoaderRoute: typeof StudioContractsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/calendar': {
      id: '/studio/calendar'
      path: '/calendar'
      fullPath: '/studio/calendar'
      preLoaderRoute: typeof StudioCalendarRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/briefings': {
      id: '/studio/briefings'
      path: '/briefings'
      fullPath: '/studio/briefings'
      preLoaderRoute: typeof StudioBriefingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/approval-queue': {
      id: '/studio/approval-queue'
      path: '/approval-queue'
      fullPath: '/studio/approval-queue'
      preLoaderRoute: typeof StudioApprovalQueueRouteImport
      parentRoute: typeof StudioRoute
    }
    '/portal/welcome': {
      id: '/portal/welcome'
      path: '/welcome'
      fullPath: '/portal/welcome'
      preLoaderRoute: typeof PortalWelcomeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/timeline': {
      id: '/portal/timeline'
      path: '/timeline'
      fullPath: '/portal/timeline'
      preLoaderRoute: typeof PortalTimelineRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/resources': {
      id: '/portal/resources'
      path: '/resources'
      fullPath: '/portal/resources'
      preLoaderRoute: typeof PortalResourcesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/questionnaires': {
      id: '/portal/questionnaires'
      path: '/questionnaires'
      fullPath: '/portal/questionnaires'
      preLoaderRoute: typeof PortalQuestionnairesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/portrait-sequence': {
      id: '/portal/portrait-sequence'
      path: '/portrait-sequence'
      fullPath: '/portal/portrait-sequence'
      preLoaderRoute: typeof PortalPortraitSequenceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/gallery': {
      id: '/portal/gallery'
      path: '/gallery'
      fullPath: '/portal/gallery'
      preLoaderRoute: typeof PortalGalleryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/engagement': {
      id: '/portal/engagement'
      path: '/engagement'
      fullPath: '/portal/engagement'
      preLoaderRoute: typeof PortalEngagementRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/activity': {
      id: '/portal/activity'
      path: '/activity'
      fullPath: '/portal/activity'
      preLoaderRoute: typeof PortalActivityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRoute
    }
    '/studio/clients/': {
      id: '/studio/clients/'
      path: '/clients'
      fullPath: '/studio/clients/'
      preLoaderRoute: typeof StudioClientsIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/portal/account/': {
      id: '/portal/account/'
      path: '/'
      fullPath: '/portal/account/'
      preLoaderRoute: typeof PortalAccountIndexRouteImport
      parentRoute: typeof PortalAccountRoute
    }
    '/studio/settings/workflow': {
      id: '/studio/settings/workflow'
      path: '/workflow'
      fullPath: '/studio/settings/workflow'
      preLoaderRoute: typeof StudioSettingsWorkflowRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/team': {
      id: '/studio/settings/team'
      path: '/team'
      fullPath: '/studio/settings/team'
      preLoaderRoute: typeof StudioSettingsTeamRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/studio-profile': {
      id: '/studio/settings/studio-profile'
      path: '/studio-profile'
      fullPath: '/studio/settings/studio-profile'
      preLoaderRoute: typeof StudioSettingsStudioProfileRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/storage': {
      id: '/studio/settings/storage'
      path: '/storage'
      fullPath: '/studio/settings/storage'
      preLoaderRoute: typeof StudioSettingsStorageRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/resources': {
      id: '/studio/settings/resources'
      path: '/resources'
      fullPath: '/studio/settings/resources'
      preLoaderRoute: typeof StudioSettingsResourcesRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/profile': {
      id: '/studio/settings/profile'
      path: '/profile'
      fullPath: '/studio/settings/profile'
      preLoaderRoute: typeof StudioSettingsProfileRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/integrations': {
      id: '/studio/settings/integrations'
      path: '/integrations'
      fullPath: '/studio/settings/integrations'
      preLoaderRoute: typeof StudioSettingsIntegrationsRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/email-templates': {
      id: '/studio/settings/email-templates'
      path: '/email-templates'
      fullPath: '/studio/settings/email-templates'
      preLoaderRoute: typeof StudioSettingsEmailTemplatesRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/contractors': {
      id: '/studio/settings/contractors'
      path: '/contractors'
      fullPath: '/studio/settings/contractors'
      preLoaderRoute: typeof StudioSettingsContractorsRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/contract-templates': {
      id: '/studio/settings/contract-templates'
      path: '/contract-templates'
      fullPath: '/studio/settings/contract-templates'
      preLoaderRoute: typeof StudioSettingsContractTemplatesRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/contract-defaults': {
      id: '/studio/settings/contract-defaults'
      path: '/contract-defaults'
      fullPath: '/studio/settings/contract-defaults'
      preLoaderRoute: typeof StudioSettingsContractDefaultsRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/calendar': {
      id: '/studio/settings/calendar'
      path: '/calendar'
      fullPath: '/studio/settings/calendar'
      preLoaderRoute: typeof StudioSettingsCalendarRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/activity-log': {
      id: '/studio/settings/activity-log'
      path: '/activity-log'
      fullPath: '/studio/settings/activity-log'
      preLoaderRoute: typeof StudioSettingsActivityLogRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/queue/hidden': {
      id: '/studio/queue/hidden'
      path: '/hidden'
      fullPath: '/studio/queue/hidden'
      preLoaderRoute: typeof StudioQueueHiddenRouteImport
      parentRoute: typeof StudioQueueRoute
    }
    '/studio/pipeline/sales': {
      id: '/studio/pipeline/sales'
      path: '/pipeline/sales'
      fullPath: '/studio/pipeline/sales'
      preLoaderRoute: typeof StudioPipelineSalesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/pipeline/production': {
      id: '/studio/pipeline/production'
      path: '/pipeline/production'
      fullPath: '/studio/pipeline/production'
      preLoaderRoute: typeof StudioPipelineProductionRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/contracts/templates': {
      id: '/studio/contracts/templates'
      path: '/templates'
      fullPath: '/studio/contracts/templates'
      preLoaderRoute: typeof StudioContractsTemplatesRouteImport
      parentRoute: typeof StudioContractsRoute
    }
    '/studio/clients/$id': {
      id: '/studio/clients/$id'
      path: '/clients/$id'
      fullPath: '/studio/clients/$id'
      preLoaderRoute: typeof StudioClientsIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/briefings/$id': {
      id: '/studio/briefings/$id'
      path: '/$id'
      fullPath: '/studio/briefings/$id'
      preLoaderRoute: typeof StudioBriefingsIdRouteImport
      parentRoute: typeof StudioBriefingsRoute
    }
    '/sign/contract/$contractId': {
      id: '/sign/contract/$contractId'
      path: '/sign/contract/$contractId'
      fullPath: '/sign/contract/$contractId'
      preLoaderRoute: typeof SignContractContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/account/security': {
      id: '/portal/account/security'
      path: '/security'
      fullPath: '/portal/account/security'
      preLoaderRoute: typeof PortalAccountSecurityRouteImport
      parentRoute: typeof PortalAccountRoute
    }
    '/portal/account/partner': {
      id: '/portal/account/partner'
      path: '/partner'
      fullPath: '/portal/account/partner'
      preLoaderRoute: typeof PortalAccountPartnerRouteImport
      parentRoute: typeof PortalAccountRoute
    }
    '/portal/account/notifications': {
      id: '/portal/account/notifications'
      path: '/notifications'
      fullPath: '/portal/account/notifications'
      preLoaderRoute: typeof PortalAccountNotificationsRouteImport
      parentRoute: typeof PortalAccountRoute
    }
    '/studio/settings/emails/': {
      id: '/studio/settings/emails/'
      path: '/emails'
      fullPath: '/studio/settings/emails/'
      preLoaderRoute: typeof StudioSettingsEmailsIndexRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/settings/emails/$emailType': {
      id: '/studio/settings/emails/$emailType'
      path: '/emails/$emailType'
      fullPath: '/studio/settings/emails/$emailType'
      preLoaderRoute: typeof StudioSettingsEmailsEmailTypeRouteImport
      parentRoute: typeof StudioSettingsRoute
    }
    '/studio/contracts/templates/$id': {
      id: '/studio/contracts/templates/$id'
      path: '/$id'
      fullPath: '/studio/contracts/templates/$id'
      preLoaderRoute: typeof StudioContractsTemplatesIdRouteImport
      parentRoute: typeof StudioContractsTemplatesRoute
    }
    '/studio/clients/$id_/sourcing': {
      id: '/studio/clients/$id_/sourcing'
      path: '/clients/$id/sourcing'
      fullPath: '/studio/clients/$id/sourcing'
      preLoaderRoute: typeof StudioClientsIdSourcingRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface PortalAccountRouteChildren {
  PortalAccountNotificationsRoute: typeof PortalAccountNotificationsRoute
  PortalAccountPartnerRoute: typeof PortalAccountPartnerRoute
  PortalAccountSecurityRoute: typeof PortalAccountSecurityRoute
  PortalAccountIndexRoute: typeof PortalAccountIndexRoute
}

const PortalAccountRouteChildren: PortalAccountRouteChildren = {
  PortalAccountNotificationsRoute: PortalAccountNotificationsRoute,
  PortalAccountPartnerRoute: PortalAccountPartnerRoute,
  PortalAccountSecurityRoute: PortalAccountSecurityRoute,
  PortalAccountIndexRoute: PortalAccountIndexRoute,
}

const PortalAccountRouteWithChildren = PortalAccountRoute._addFileChildren(
  PortalAccountRouteChildren,
)

interface PortalRouteChildren {
  PortalAccountRoute: typeof PortalAccountRouteWithChildren
  PortalActivityRoute: typeof PortalActivityRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalEngagementRoute: typeof PortalEngagementRoute
  PortalGalleryRoute: typeof PortalGalleryRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalPortraitSequenceRoute: typeof PortalPortraitSequenceRoute
  PortalQuestionnairesRoute: typeof PortalQuestionnairesRoute
  PortalResourcesRoute: typeof PortalResourcesRoute
  PortalTimelineRoute: typeof PortalTimelineRoute
  PortalWelcomeRoute: typeof PortalWelcomeRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountRoute: PortalAccountRouteWithChildren,
  PortalActivityRoute: PortalActivityRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalEngagementRoute: PortalEngagementRoute,
  PortalGalleryRoute: PortalGalleryRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalPortraitSequenceRoute: PortalPortraitSequenceRoute,
  PortalQuestionnairesRoute: PortalQuestionnairesRoute,
  PortalResourcesRoute: PortalResourcesRoute,
  PortalTimelineRoute: PortalTimelineRoute,
  PortalWelcomeRoute: PortalWelcomeRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface StudioBriefingsRouteChildren {
  StudioBriefingsIdRoute: typeof StudioBriefingsIdRoute
}

const StudioBriefingsRouteChildren: StudioBriefingsRouteChildren = {
  StudioBriefingsIdRoute: StudioBriefingsIdRoute,
}

const StudioBriefingsRouteWithChildren = StudioBriefingsRoute._addFileChildren(
  StudioBriefingsRouteChildren,
)

interface StudioContractsTemplatesRouteChildren {
  StudioContractsTemplatesIdRoute: typeof StudioContractsTemplatesIdRoute
}

const StudioContractsTemplatesRouteChildren: StudioContractsTemplatesRouteChildren =
  {
    StudioContractsTemplatesIdRoute: StudioContractsTemplatesIdRoute,
  }

const StudioContractsTemplatesRouteWithChildren =
  StudioContractsTemplatesRoute._addFileChildren(
    StudioContractsTemplatesRouteChildren,
  )

interface StudioContractsRouteChildren {
  StudioContractsTemplatesRoute: typeof StudioContractsTemplatesRouteWithChildren
}

const StudioContractsRouteChildren: StudioContractsRouteChildren = {
  StudioContractsTemplatesRoute: StudioContractsTemplatesRouteWithChildren,
}

const StudioContractsRouteWithChildren = StudioContractsRoute._addFileChildren(
  StudioContractsRouteChildren,
)

interface StudioQueueRouteChildren {
  StudioQueueHiddenRoute: typeof StudioQueueHiddenRoute
}

const StudioQueueRouteChildren: StudioQueueRouteChildren = {
  StudioQueueHiddenRoute: StudioQueueHiddenRoute,
}

const StudioQueueRouteWithChildren = StudioQueueRoute._addFileChildren(
  StudioQueueRouteChildren,
)

interface StudioSettingsRouteChildren {
  StudioSettingsActivityLogRoute: typeof StudioSettingsActivityLogRoute
  StudioSettingsCalendarRoute: typeof StudioSettingsCalendarRoute
  StudioSettingsContractDefaultsRoute: typeof StudioSettingsContractDefaultsRoute
  StudioSettingsContractTemplatesRoute: typeof StudioSettingsContractTemplatesRoute
  StudioSettingsContractorsRoute: typeof StudioSettingsContractorsRoute
  StudioSettingsEmailTemplatesRoute: typeof StudioSettingsEmailTemplatesRoute
  StudioSettingsIntegrationsRoute: typeof StudioSettingsIntegrationsRoute
  StudioSettingsProfileRoute: typeof StudioSettingsProfileRoute
  StudioSettingsResourcesRoute: typeof StudioSettingsResourcesRoute
  StudioSettingsStorageRoute: typeof StudioSettingsStorageRoute
  StudioSettingsStudioProfileRoute: typeof StudioSettingsStudioProfileRoute
  StudioSettingsTeamRoute: typeof StudioSettingsTeamRoute
  StudioSettingsWorkflowRoute: typeof StudioSettingsWorkflowRoute
  StudioSettingsEmailsEmailTypeRoute: typeof StudioSettingsEmailsEmailTypeRoute
  StudioSettingsEmailsIndexRoute: typeof StudioSettingsEmailsIndexRoute
}

const StudioSettingsRouteChildren: StudioSettingsRouteChildren = {
  StudioSettingsActivityLogRoute: StudioSettingsActivityLogRoute,
  StudioSettingsCalendarRoute: StudioSettingsCalendarRoute,
  StudioSettingsContractDefaultsRoute: StudioSettingsContractDefaultsRoute,
  StudioSettingsContractTemplatesRoute: StudioSettingsContractTemplatesRoute,
  StudioSettingsContractorsRoute: StudioSettingsContractorsRoute,
  StudioSettingsEmailTemplatesRoute: StudioSettingsEmailTemplatesRoute,
  StudioSettingsIntegrationsRoute: StudioSettingsIntegrationsRoute,
  StudioSettingsProfileRoute: StudioSettingsProfileRoute,
  StudioSettingsResourcesRoute: StudioSettingsResourcesRoute,
  StudioSettingsStorageRoute: StudioSettingsStorageRoute,
  StudioSettingsStudioProfileRoute: StudioSettingsStudioProfileRoute,
  StudioSettingsTeamRoute: StudioSettingsTeamRoute,
  StudioSettingsWorkflowRoute: StudioSettingsWorkflowRoute,
  StudioSettingsEmailsEmailTypeRoute: StudioSettingsEmailsEmailTypeRoute,
  StudioSettingsEmailsIndexRoute: StudioSettingsEmailsIndexRoute,
}

const StudioSettingsRouteWithChildren = StudioSettingsRoute._addFileChildren(
  StudioSettingsRouteChildren,
)

interface StudioRouteChildren {
  StudioApprovalQueueRoute: typeof StudioApprovalQueueRoute
  StudioBriefingsRoute: typeof StudioBriefingsRouteWithChildren
  StudioCalendarRoute: typeof StudioCalendarRoute
  StudioContractsRoute: typeof StudioContractsRouteWithChildren
  StudioFinancialsRoute: typeof StudioFinancialsRoute
  StudioFormsRoute: typeof StudioFormsRoute
  StudioGalleriesRoute: typeof StudioGalleriesRoute
  StudioInvoicesRoute: typeof StudioInvoicesRoute
  StudioMessagesRoute: typeof StudioMessagesRoute
  StudioQueueRoute: typeof StudioQueueRouteWithChildren
  StudioResourcesRoute: typeof StudioResourcesRoute
  StudioSettingsRoute: typeof StudioSettingsRouteWithChildren
  StudioTasksRoute: typeof StudioTasksRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioClientsIdRoute: typeof StudioClientsIdRoute
  StudioPipelineProductionRoute: typeof StudioPipelineProductionRoute
  StudioPipelineSalesRoute: typeof StudioPipelineSalesRoute
  StudioClientsIndexRoute: typeof StudioClientsIndexRoute
  StudioClientsIdSourcingRoute: typeof StudioClientsIdSourcingRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioApprovalQueueRoute: StudioApprovalQueueRoute,
  StudioBriefingsRoute: StudioBriefingsRouteWithChildren,
  StudioCalendarRoute: StudioCalendarRoute,
  StudioContractsRoute: StudioContractsRouteWithChildren,
  StudioFinancialsRoute: StudioFinancialsRoute,
  StudioFormsRoute: StudioFormsRoute,
  StudioGalleriesRoute: StudioGalleriesRoute,
  StudioInvoicesRoute: StudioInvoicesRoute,
  StudioMessagesRoute: StudioMessagesRoute,
  StudioQueueRoute: StudioQueueRouteWithChildren,
  StudioResourcesRoute: StudioResourcesRoute,
  StudioSettingsRoute: StudioSettingsRouteWithChildren,
  StudioTasksRoute: StudioTasksRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioClientsIdRoute: StudioClientsIdRoute,
  StudioPipelineProductionRoute: StudioPipelineProductionRoute,
  StudioPipelineSalesRoute: StudioPipelineSalesRoute,
  StudioClientsIndexRoute: StudioClientsIndexRoute,
  StudioClientsIdSourcingRoute: StudioClientsIdSourcingRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  SignContractContractIdRoute: SignContractContractIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
